# Generated by Django 3.1.6 on 2021-07-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='expense_category',
            name='title',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='income',
            name='title',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='income_category',
            name='title',
            field=models.CharField(max_length=12),
        ),
    ]
