# Generated by Django 3.1.6 on 2021-07-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20210702_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='income',
            new_name='amount',
        ),
    ]
