# Generated by Django 3.1.6 on 2022-02-06 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20210707_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-id']},
        ),
    ]
